sudo: required
services:
  - docker

before_install:
  - docker build -t cohenbond537/docker-react -f Dockerfile.dev .

script:
  - docker run cohenbond537/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "aws-devops-cohen"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: AKIAWPYRN2NHQEDTVZPP
  secret_access_key:
    secure: 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

